### ISSUE TITLE
Permalinks are generated incorrectly when relative_link=true

### ISSUE THREAD

**Issue by marlonpatrick10** [LouisBarranqueiro/tranquilpeak-hexo-theme#45]
Hi Louis, 
I do not know if this issue is in your theme or is it a bug hexo, but when I set relative_link to true my permalinks are generated incorrectly.

relative_link=false: http://localhost:4000/2015/07/02/hello-world/ (expected url)
relative_link=true: http://localhost:4000/2015/07/02/index.html (wrong url)

Has any problem if I set relative_link to false?

Hexo version that I used is 3.1.1:
hexo: 3.1.1
os: Linux 3.13.0-55-generic linux ia32
http_parser: 2.3
node: 0.12.5
v8: 3.28.71.19
uv: 1.6.1
zlib: 1.2.8
modules: 14
openssl: 1.0.1o

**Comment by LouisBarranqueiro** [comment]
Hi man. Can you show me the source code of your page. I fixed some problems with `relative: true` but there is still some bugs that come from Hexo (3.1.1). So I recommend to use `relative_link` to `false`. Currently, all links are relative even with  `relative` to `false`.

**Comment by marlonpatrick10** [comment]
Hello Louis, there's nothing special in my code. To simulate this problem simply just download the latest version of tranquealpeak (1.1.1) and then set relative_link to true.

But did a test with the default theme (landscape) and resulted in the same problem. Thus, I am using relative_link = false.

It might be interesting you say something about the user documentation.

**Comment by LouisBarranqueiro** [comment]
Hi Patrick. Yeah I fixed this in this [commit](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/commit/6de7f553e8a6fc3a8271ac14030da1b2d88977e0).   
It works perfectly except you enter the blog url withouth the end `/` like this : `http://localhost:4000/tranquilpeak-hexo-theme`. In this case, all assets are not loaded. Other case, the root relative link is not correctly displayed, there is always a `/` in addition : `../..//`. These bugs come from Hexo. **That why I still recommand to use `relative`to `false`.** In the new version, I will add a section in user documentation to inform users about this issue.

I will release a new version of the theme soon :) (in two days I think). Thanks you for your feedback. :)

**Comment by LouisBarranqueiro** [comment]
I just found a solution to fix the second problem.

**Comment by LouisBarranqueiro** [comment]
I had an issue on Hexo : [#1381](https://github.com/hexojs/hexo/issues/1381)

**Comment by marlonpatrick10** [comment]
Thank you Louis, I'm using relative_link=false as you recommends.

**Comment by hanmomhanda** [comment]
Hi, Louis.
This is a really fantastic theme!!

I have the same problem as Patrick's.

I fixed the problem by just setting `relative_link: false` in `_config.yml` of Hexo.

But the [official user document](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/blob/master/docs/user.md#enable-relative-links) still says, 

> You have to set relative_link to true otherwise features like navigation bar will not work correctly.

So, I think the document also needs to be modified.

Thank you for the great theme. ^^

**Comment by LouisBarranqueiro** [comment]
Yeah, this is what I said 4 comments above :p. Thanks you man :)

**Comment by LouisBarranqueiro** [comment]
[Tranquilpeak 1.2.0](https://github.com/LouisBarranqueiro/tranquilpeak-hexo-theme/releases/tag/v1.2.0) is here. In user documentation, it's recommended to use Hexo 3.0.x and still disable relative links be cause issue [#1381](https://github.com/hexojs/hexo/issues/1381) is still not resolved. Hexo 3.1.x have more critical problem to generate relative links. An issue is open to fix this [#1401](https://github.com/hexojs/hexo/issues/1401).
